version: '3.8'
services:
  db:
    image: mysql:8.0.29
    restart: unless-stopped
    container_name: mercado_db
    ports:
      - "3307:3306"  # Remova o bind ao 127.0.0.1 para facilitar o acesso entre containers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market_management
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_APP: src/run.py
      FLASK_ENV: development
      DATABASE_URI: "mysql+mysqlconnector://root:root@mercado_db:3306/market_management"
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend/ms-market
    container_name: frontend_mercado
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/ms-market:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  mysql_data:

networks:
  market_management_network:
    driver: bridge